-- SpendInCheck schema for PostgreSQL (Supabase deployment only).
-- The graded project uses schema.sql on MySQL; this is a port for hosting.

DROP TABLE IF EXISTS budgets CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS investments CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    user_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30) NOT NULL UNIQUE,
    email         VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    category_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    category_name VARCHAR(50) NOT NULL,
    category_type VARCHAR(10) NOT NULL CHECK (category_type IN ('Income','Expense')),
    CONSTRAINT uniq_user_category UNIQUE (user_id, category_name)
);

CREATE TABLE transactions (
    transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    txn_date       DATE NOT NULL,
    category_id    INT NOT NULL REFERENCES categories(category_id),
    amount         DECIMAL(10,2) NOT NULL,
    txn_type       VARCHAR(10) NOT NULL CHECK (txn_type IN ('Income','Expense')),
    description    VARCHAR(255)
);

CREATE TABLE budgets (
    budget_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    category_id  INT NOT NULL REFERENCES categories(category_id),
    month_year   VARCHAR(7) NOT NULL,
    budget_limit DECIMAL(10,2) NOT NULL,
    CONSTRAINT uniq_cat_month UNIQUE (category_id, month_year)
);

CREATE TABLE investments (
    investment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    asset_name    VARCHAR(100) NOT NULL,
    asset_type    VARCHAR(20) NOT NULL CHECK (asset_type IN ('Stock','Mutual Fund','FD')),
    buy_date      DATE NOT NULL,
    buy_price     DECIMAL(10,2) NOT NULL,
    quantity      DECIMAL(10,4) NOT NULL,
    current_price DECIMAL(10,2) NOT NULL
);
