-- SpendInCheck schema for PostgreSQL (Supabase deployment only).
-- The graded project uses schema.sql on MySQL; this is a port for hosting.

DROP TABLE IF EXISTS budgets CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS investments CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    user_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30) NOT NULL UNIQUE,
    email         VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    category_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    category_name VARCHAR(50) NOT NULL,
    category_type VARCHAR(10) NOT NULL CHECK (category_type IN ('Income','Expense')),
    CONSTRAINT uniq_user_category UNIQUE (user_id, category_name)
);

CREATE TABLE transactions (
    transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    txn_date       DATE NOT NULL,
    category_id    INT NOT NULL REFERENCES categories(category_id),
    amount         DECIMAL(10,2) NOT NULL,
    txn_type       VARCHAR(10) NOT NULL CHECK (txn_type IN ('Income','Expense')),
    description    VARCHAR(255)
);

CREATE TABLE budgets (
    budget_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  INT NOT NULL REFERENCES categories(category_id),
    month_year   VARCHAR(7) NOT NULL,
    budget_limit DECIMAL(10,2) NOT NULL,
    CONSTRAINT uniq_cat_month UNIQUE (category_id, month_year)
);

CREATE TABLE investments (
    investment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name    VARCHAR(100) NOT NULL,
    asset_type    VARCHAR(20) NOT NULL CHECK (asset_type IN ('Stock','Mutual Fund','FD')),
    buy_date      DATE NOT NULL,
    buy_price     DECIMAL(10,2) NOT NULL,
    quantity      DECIMAL(10,4) NOT NULL,
    current_price DECIMAL(10,2) NOT NULL
);
-- Seed data: categories
INSERT INTO categories (category_name, category_type) VALUES
('Salary',        'Income'),
('Freelance',      'Income'),
('Groceries',      'Expense'),
('Rent',           'Expense'),
('Transport',      'Expense'),
('Entertainment',  'Expense'),
('Utilities',      'Expense'),
('Dining Out',     'Expense');

-- Seed data: transactions spread across three months (2026-06, 2026-07, 2026-08)
INSERT INTO transactions (txn_date, category_id, amount, txn_type, description) VALUES
('2026-06-01', 1, 55000.00, 'Income',  'June salary'),
('2026-06-02', 4, 15000.00, 'Expense', 'June rent'),
('2026-06-05', 3,  3200.50, 'Expense', 'Weekly groceries'),
('2026-06-10', 5,  1200.00, 'Expense', 'Fuel and cab rides'),
('2026-06-15', 6,   800.00, 'Expense', 'Movie night'),
('2026-06-20', 7,  2100.00, 'Expense', 'Electricity bill'),
('2026-06-25', 2,  8000.00, 'Income',  'Freelance web project'),
('2026-07-01', 1, 55000.00, 'Income',  'July salary'),
('2026-07-02', 4, 15000.00, 'Expense', 'July rent'),
('2026-07-06', 3,  2900.00, 'Expense', 'Weekly groceries'),
('2026-07-11', 5,  1500.00, 'Expense', 'Metro pass'),
('2026-07-14', 8,  1100.00, 'Expense', 'Dinner with friends'),
('2026-07-18', 6,  600.00,  'Expense', 'Streaming subscription'),
('2026-07-22', 7,  2300.00, 'Expense', 'Electricity bill'),
('2026-08-01', 1, 56000.00, 'Income',  'August salary'),
('2026-08-02', 4, 15000.00, 'Expense', 'August rent'),
('2026-08-05', 3,  3400.00, 'Expense', 'Weekly groceries'),
('2026-08-09', 5,  1300.00, 'Expense', 'Fuel'),
('2026-08-12', 6,  950.00,  'Expense', 'Concert ticket'),
('2026-08-19', 8,  1400.00, 'Expense', 'Weekend brunch');

-- Seed data: budgets (a few categories, current months)
INSERT INTO budgets (category_id, month_year, budget_limit) VALUES
(3, '2026-06', 4000.00),
(4, '2026-06', 15000.00),
(6, '2026-06', 1000.00),
(3, '2026-07', 4000.00),
(7, '2026-07', 2000.00),
(3, '2026-08', 3500.00),
(6, '2026-08', 1000.00);

-- Seed data: investments (mix of stock/mutual fund/FD)
INSERT INTO investments (asset_name, asset_type, buy_date, buy_price, quantity, current_price) VALUES
('Tata Motors',            'Stock',       '2026-02-10',  650.00, 20.0000,  720.50),
('Infosys',                'Stock',       '2026-03-15', 1450.00, 10.0000, 1390.00),
('HDFC Flexi Cap Fund',    'Mutual Fund', '2026-01-20',   45.20, 500.0000,   48.75),
('SBI Bluechip Fund',      'Mutual Fund', '2026-04-05',   62.10, 300.0000,   60.90),
('SBI Fixed Deposit',      'FD',          '2026-01-01', 100000.00, 1.0000, 104500.00),
('Reliance Industries',    'Stock',       '2026-05-12', 2450.00,  8.0000, 2510.75);
